name: Deploy Website

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact (public folder)
        uses: actions/upload-pages-artifact@v3
        with:
          path: BaiTap7/public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
